version: "3.4"
x-environment: &QUICKSTART_ENVIRONMENT
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET: ${PLAID_SECRET}
  PLAID_PRODUCTS: transactions
  PLAID_COUNTRY_CODES: US,CA
  PLAID_REDIRECT_URI:
services:
  go:
    build:
      context: .
      dockerfile: ./go/Dockerfile
    ports: ["8000:8000"]
    environment:
      << : *QUICKSTART_ENVIRONMENT
  java:
    build: 
      context: .
      dockerfile: ./java/Dockerfile
    ports: ["8000:8000"]
    environment:
      << : *QUICKSTART_ENVIRONMENT
  node:
    build: 
      context: .
      dockerfile: ./node/Dockerfile
    ports: ["8000:8000"]
    environment:
      << : *QUICKSTART_ENVIRONMENT
  python:
    build: 
      context: .
      dockerfile: ./python/Dockerfile
    ports: ["8000:8000"]
    environment:
      << : *QUICKSTART_ENVIRONMENT
  ruby:
    build: 
      context: .
      dockerfile: ./ruby/Dockerfile
    ports: ["8000:8000"]
    environment:
      << : *QUICKSTART_ENVIRONMENT
